on: [push]

jobs:
  build_docs_job:     
    if: (github.repository == 'DavidLeoni/jupman') && ((github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/dev') || (github.ref == 'refs/heads/themed'))
    runs-on: ubuntu-18.04
    name: Build docs    
    steps:   
    - name: Install deps
      run: |
        sudo apt-get install tree
    - name: sets environment 
      run: |        
        echo "::set-env name=GIT_TAG::${GITHUB_REF##*/}"
        echo "::set-env name=VERSION::${GITHUB_REF##*/}"
        echo "::set-env name=LANGUAGE::en"        
    - name: apply docs version renaming
      if: env.GIT_TAG == 'master'
      run: echo "::set-env name=VERSION::latest"
    - name: sets WEB_PATH
      run: echo "::set-env name=WEB_PATH::${{env.LANGUAGE}}/${{env.VERSION}}"
    - name: Run Sphinx in RTD docker      
      uses: DavidLeoni/readthedocs-to-actions@v1.2
      with:
        RTD_PRJ_NAME: jupman        
        GIT_URL: https://github.com/${{ github.repository }}.git
        GIT_TAG: ${{ env.GIT_TAG }}
        VERSION: ${{ env.VERSION }}
        REQUIREMENTS: requirements-build.txt
        LANGUAGE: ${{ env.LANGUAGE }}
        RTD_HTML_SINGLE: false
        RTD_HTML_EXT: false      
        GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
    - name: Show workspace output
      run: |        
        tree -aC $GITHUB_WORKSPACE
    - name: Commit documentation changes
      run: |
        git clone https://github.com/${{ github.repository }}.git --branch gh-pages --single-branch gh-pages
        
        mkdir -p gh-pages/${{ env.WEB_PATH }}
        cp -r $GITHUB_WORKSPACE/html/* gh-pages/${{ env.WEB_PATH }}
        if compgen -G "$GITHUB_WORKSPACE/latex/*.pdf" > /dev/null; then
             cp -r $GITHUB_WORKSPACE/latex/*.pdf gh-pages/${{ env.WEB_PATH }}
        else
             echo "ERROR: NO PDF FILES WHERE GENERATED!"
        fi
        if compgen -G "$GITHUB_WORKSPACE/epub/*.epub" > /dev/null; then
             cp -r $GITHUB_WORKSPACE/epub/*.epub gh-pages/${{ env.WEB_PATH }}
        else
             echo "ERROR: NO EPUB FILES WHERE GENERATED!"
        fi

        # note: html zip is already provided by Github
        cd gh-pages        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .      
        touch .nojekyll
        git add .nojekyll  # explicit, otherwise is ignored
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: deploy to custom server
      run: |
        # Custom deploy, you don't need this
        if [ ! -z "${{ secrets.DAVAPI_URL }}" ]; then 
            curl --silent --digest --user ${{ secrets.DAVAPI_CREDENTIALS}} ${{ secrets.DAVAPI_URL }}
        fi